### ISSUE TITLE
Error with the tag og:image

### ISSUE THREAD

**Issue by Uthanien** [ernilambar/simple-life#4]
When you share a link, is not taken the header image of the post, instead take the image of the header site. In the facebook depurator, says that tag og:image is not explicitly set.

Example: https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.thatswhatfespisaid.com%2Fcine%2Flos-colonos-2023%2F

**Comment by ernilambar** [comment]
@Uthanien Theme in the WordPress directory is not allowed to add such tag in the header. You need to use plugins for that. You will find several plugins to add such `og` tags. Few examples: https://wordpress.org/plugins/wonderm00ns-simple-facebook-open-graph-tags/ or https://wordpress.org/plugins/wordpress-seo/
